language: node_js
install: gem install fpm
node_js:
- 0.1
env:
  global:
  - VERSION_NUMBER="`git describe --tags | sed 's/^[a-z,A-Z]*//'`"
  - REAL_GIT_BRANCH="`git for-each-ref --format='%(objectname) %(refname:short)' refs/heads
    | grep $TRAVIS_COMMIT | awk '{print $2}'`"
after_success:
- echo version_number $VERSION_NUMBER
- echo real_get_branch $REAL_GIT_BRANCH
- rm -rf OpenROV/build-*
- 'fpm -f -m info@openrov.com -s dir -t deb -a all -n openrov-nolagcamera -d http://54.187.8.25:8080/job/OpenROV-DEBIAN-023-packages-mjpegstreamer/lastSuccessfulBuild/artifact/work/packages/openrov-mjpeg-streamer_2.0-1_armhf.deb
  -v $VERSION_NUMBER-$REAL_GIT_BRANCH --before-install=linux/openrov-nolagcamera-beforeinstall.sh
  --after-install=linux/openrov-nolagcamera-afterinstall.sh --before-remove=linux/openrov-nolagcamera-beforeremove.sh
  --description ''OpenROV NoLagCamera'' .=/opt/openrov/nolagcamera '
- mkdir build
- cp *.deb build/openrov-nolagcamera_latest-${REAL_GIT_BRANCH}_all.deb
- mv *.deb build/
deploy:
  provider: s3
  access_key_id: AKIAIUN4NNHBKIOZE2JA
  secret_access_key:
    secure: HndY8whUIMqYa07hqy6b/RvfNBrik2mpBLw0sNiXDcm0mIkT3CSm0R0/tbJK68GebmG+tjGnCf/zbcbjxHw0MwWOF50CZ+3zT0JDTu6SdclFK/nkcWZGmJ9rirBJdISF8/H8/DKyiPJnYE8QMIX2GyacNZPrmpzYiLbb7Hvq+vo=
  bucket: openrov-software-nightlies
  skip_cleanup: true
  region: us-west-2
  endpoint: bucket-name.s3-website-us-west-2.amazonaws.com
  local-dir: build
  upload-dir: nolagcamera
  acl: !ruby/string:HighLine::String public_read
  on:
    repo: BrianAdams/openrov-nolagcamera
