language: node_js
install: gem install fpm
node_js:
  - 0.10
env:
  global:
  - VERSION_NUMBER="`git describe --tags | sed 's/^[a-z,A-Z]*//'`"
  - REAL_GIT_BRANCH="`git for-each-ref --format='%(objectname) %(refname:short)' refs/heads
    | grep $TRAVIS_COMMIT | awk '{print $2}'`"
after_success:
- echo version_number $VERSION_NUMBER
- echo real_get_branch $REAL_GIT_BRANCH
- 'fpm -f -m info@openrov.com -s dir -t deb -a all -n openrov-nolagcamera -d http://54.187.8.25:8080/job/OpenROV-DEBIAN-023-packages-mjpegstreamer/lastSuccessfulBuild/artifact/work/packages/openrov-mjpeg-streamer_2.0-1_armhf.deb
  -v $VERSION_NUMBER-$REAL_GIT_BRANCH --before-install=linux/openrov-nolagcamera-beforeinstall.sh --after-install=linux/openrov-nolagcamera-afterinstall.sh --before-remove=linux/steps/step_03/openrov-nolagcamera-beforeremove.sh --description ''OpenROV NoLagCamera'' .=/opt/openrov/nolagcamera '
- mkdir build
- cp *.deb build/openrov-nolagcamera_latest-${REAL_GIT_BRANCH}_all.deb
- mv *.deb build/
