language: node_js
node_js:
  - 0.10
env:
  global:
  - VERSION_NUMBER="`git describe --tags | sed 's/^[a-z,A-Z]*//'`"
  - REAL_GIT_BRANCH="`git for-each-ref --format='%(objectname) %(refname:short)' refs/heads
    | grep $TRAVIS_COMMIT | awk '{print $2}'`"
after_success:
- echo version_number $VERSION_NUMBER
- echo real_get_branch $REAL_GIT_BRANCH
- 'fpm -f -m info@openrov.com -s dir -t deb -a all -n openrov-nolagcamera -v
  $VERSION_NUMBER-$REAL_GIT_BRANCH --description ''OpenROV NoLagCamera'' .=/opt/openrov/nolagcamera '
- mkdir build
- cp *.deb build/openrov-nolagcamera_latest-${REAL_GIT_BRANCH}_all.deb
- mv *.deb build/
